### PR TITLE
Add delete function to Employees

### LINKED ISSUE #24: Create Delete Function to Employee
# REQUIREMENTS
Add the functionality to delete an employee within the employee controller.

# Acceptance Criteria
List all required acceptance criteria
- [x] Delete Employee Function

### PR DESCRIPTION
**Pull request by SampabloC**
- Modify employees controller to add delete function called destroy.
- Add function to button Delete on _list view.
- Also add a confirmation message before delete from database.

Co-authored-by: RobertCarMed <betocarrasco3652@gmail.com>
Co-authored-by: mrivh <m.alicia.riv@gmail.com>

Resolve #24 
  
  ## Screenshots 
Confirmation Message
imagen

### CODE REVIEW

**Review by AlejandroVI99 — APPROVED** [review]
LGTM! lml

**Review by xFerchoVJ — APPROVED** [review]
LGTM!🥳

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by SEVERO96 — COMMENTED** [review]
An observation on the requirements to manage employees (CRUD operations) is
Deactivate employees instead of deleting them

**Pull request merged**
